import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { motion } from 'framer-motion';
import { Shield, ExternalLink, CheckCircle2, FileText, ArrowLeft, Search, Filter } from 'lucide-react';
import { Link } from 'react-router-dom';

const SmartCitations = () => {
  const dummyCitations = [
    {
      id: 1,
      title: 'Yuvraj Laxmilal Kanther vs The State Of Maharashtra',
      court: 'Supreme Court of India',
      date: 'March 7, 2025',
      citationId: '2025-SC-120',
      engine: 'Llama 3.2 (Legal-v1)',
      type: 'JUDGMENT',
      filename: '2025-SC-120.PDF'
    },
    {
      id: 2,
      title: 'Yogesh Kumar vs The State Of Uttar Pradesh',
      court: 'Supreme Court of India',
      date: 'March 18, 2025',
      citationId: '2025-SC-145',
      engine: 'Llama 3.2 (Legal-v1)',
      type: 'ORDER',
      filename: '2025-SC-145.PDF'
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-slate-50 min-h-screen pt-32 text-slate-900 pb-24"
    >
      <Navbar />
      <div className="max-w-5xl mx-auto px-6">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-12">
          <div className="max-w-2xl">
            <div className="flex items-center gap-2 bg-orange-50 border border-orange-100 rounded-full px-3 py-1 w-fit mb-4">
              <div className="w-1.5 h-1.5 rounded-full bg-orange-500 animate-pulse" />
              <span className="text-[10px] font-bold text-orange-600 uppercase tracking-widest">Verified Citations</span>
            </div>
            <h1 className="text-5xl font-serif text-slate-900 mb-4">Smart Citations</h1>
            <p className="text-slate-500 text-sm leading-relaxed max-w-lg">
              Every summary generated by LexAgent is backed by verified original PDF sources. View, verify, and download the primary documents here.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
              <input
                type="text"
                placeholder="Search citations..."
                className="bg-white border border-slate-200 rounded-xl pl-10 pr-4 py-2.5 text-sm w-64 focus:outline-none focus:border-orange-500/50 transition-all shadow-sm"
              />
            </div>
            <button className="p-2.5 bg-white border border-slate-200 rounded-xl text-slate-500 hover:text-orange-600 hover:border-orange-200 transition-all shadow-sm">
              <Filter size={18} />
            </button>
          </div>
        </div>

        {/* Citation Cards */}
        <div className="space-y-6">
          {dummyCitations.map((cit, idx) => (
            <motion.div
              key={cit.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              className="bg-white border border-slate-100 rounded-[2rem] p-8 shadow-sm flex flex-col lg:flex-row gap-10 items-center lg:items-stretch group hover:shadow-md transition-shadow"
            >
              {/* PDF Preview Sidebar */}
              <div className="w-full lg:w-48 flex-shrink-0">
                <div className="aspect-[3/4] bg-slate-50 rounded-2xl border border-slate-200 relative flex flex-col items-center justify-center group-hover:bg-slate-100 transition-colors">
                  <FileText className="text-slate-200 group-hover:text-slate-300 transition-colors" size={64} />
                  <div className="absolute bottom-4 left-4 right-4 bg-white/90 backdrop-blur-sm border border-slate-100 rounded-lg py-2 px-3 flex items-center justify-center">
                    <span className="text-[9px] font-mono font-bold text-slate-500 truncate">{cit.filename}</span>
                  </div>
                </div>
              </div>

              {/* Metadata Content */}
              <div className="flex-1 py-2">
                <div className="flex items-center gap-3 mb-6">
                  <div className="flex items-center gap-1.5 bg-green-50 border border-green-100 text-green-600 px-2.5 py-1 rounded-md">
                    <CheckCircle2 size={12} />
                    <span className="text-[9px] font-bold uppercase tracking-widest">Verified Source</span>
                  </div>
                  <div className="bg-slate-100 text-slate-400 px-2.5 py-1 rounded-md text-[9px] font-bold uppercase tracking-widest">
                    {cit.type}
                  </div>
                </div>

                <h2 className="text-2xl font-serif text-orange-600 mb-8 leading-tight group-hover:text-orange-700 transition-colors">
                  {cit.title}
                </h2>

                <div className="grid grid-cols-2 lg:grid-cols-4 gap-y-6 gap-x-8 mb-10">
                  <div>
                    <h4 className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Court</h4>
                    <p className="text-xs font-semibold text-slate-700">{cit.court}</p>
                  </div>
                  <div>
                    <h4 className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Date</h4>
                    <p className="text-xs font-semibold text-slate-700">{cit.date}</p>
                  </div>
                  <div>
                    <h4 className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Citation ID</h4>
                    <p className="text-xs font-semibold text-orange-600 font-mono">{cit.citationId}</p>
                  </div>
                  <div>
                    <h4 className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Engine</h4>
                    <p className="text-xs font-semibold text-slate-700">{cit.engine}</p>
                  </div>
                </div>

                <div className="flex flex-wrap gap-4">
                  <button className="bg-orange-600 hover:bg-orange-700 text-white px-6 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all shadow-sm">
                    View Source PDF <ExternalLink size={14} />
                  </button>
                  <button className="bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 px-6 py-2.5 rounded-xl text-xs font-bold transition-all shadow-sm">
                    Download Metadata
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
      <Footer />
    </motion.div>
  );
};


export default SmartCitations;
